### PR TITLE
Fix #44, CS_RecomputeAppChildTask wrong function key

### LINKED ISSUE #44: CS_RecomputeAppChildTask_Test_DefEntryId sets up handler for wrong function key
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/CS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**

The CS_RecomputeAppChildTask_Test_DefEntryId sets the handler `CS_COMPUTE_TEST_CFE_ES_GetModuleInfoHandler1` for the function key `CFE_ES_GetAppInfo` when it should use the key `CFE_ES_GetModuleInfo`. The function under test, `CS_RecomputeAppChildTask` does not call `CFE_ES_GetAppInfo`, but rather CFE_ES_GetModuleInfo, which in turn calls `CFE_GetAppInfo`. Without the handler set for this function, some properties of  `AppInfo` in the test may not be set and will cause the test to fail on some systems.

**To Reproduce**
1. Build as usual 
2. Navigate to unit-tests of cs in build tree (for me, `build/intel64/default_intel64/apps/cs/unit-test`)
3. Run `ctest -vvv --output-on-failure`
4. See test errors:

```
[BEGIN] 33 CS_RecomputeAppChildTask_Test_DefEntryI
[ PASS] 33.001 cs_compute_tests.c:1577 - CS_AppData.RecomputeAppEntryPtr->State (99) == 99 (99)
[ PASS] 33.002 cs_compute_tests.c:1578 - CS_AppData.DefAppTblPtr[CS_AppData.ChildTaskEntryID].State (1) == CS_STATE_ENABLED (1)
[ FAIL] 33.003 cs_compute_tests.c:1579 - CS_AppData.RecomputeAppEntryPtr->TempChecksumValue (1) == 0 (0)
[ FAIL] 33.004 cs_compute_tests.c:1580 - CS_AppData.RecomputeAppEntryPtr->ByteOffset (2) == 0 (0)
[ FAIL] 33.005 cs_compute_tests.c:1581 - CS_AppData.RecomputeAppEntryPtr->ComputedYet (0) == true (1)
[ FAIL] 33.006 cs_compute_tests.c:1583 - context_CFE_EVS_SendEvent[0].EventID (128) == CS_RECOMPUTE_FINISH_APP_INF_EID (99)
[ FAIL] 33.007 cs_compute_tests.c:1584 - context_CFE_EVS_SendEvent[0].EventType (1) == CFE_EVS_EventType_INFORMATION (2)
[ FAIL] 33.008 cs_compute_tests.c:1587 - String: 'App %s recompute finished. New baseline is 0x%08X' == 'CS cannot get a valid address for %s, due to the platform'
[ PASS] 33.009 cs_compute_tests.c:1589 - CS_AppData.HkPacket.RecomputeInProgress (0) == false (0)
[ FAIL] 33.010 cs_compute_tests.c:1591 - CallCount CFE_EVS_SendEvent() (3) == 1 (1)
[  END] 33 CS_RecomputeAppChildTask_Test_DefEntryI TOTAL::10    PASS::3     FAIL::7     MIR::0     TSF::0     TTF::0     WARN::0   
```

**Expected behavior**
The test should pass.

**Code snips**
If applicable, add references to the software.
https://github.com/nasa/CS/blob/3458f6578520a042fbfb1df58e7523bc79855d54/unit-test/cs_compute_tests.c#L1571

**System observed on:**
 - CS release tag draco-rc3
 - Hardware: x86_64 Intel
 - OS:  CentOS 7
 - Versions: cFE draco-rc3, OSAL draco-rc3, PSP draco-rc2

**Additional context**

**Reporter Info**
Full name and company/organization if applicable
Isaac Rowe, NASA JSC (Jacobs Technology)

### PR DESCRIPTION
**Pull request by irowebbn**

### CODE REVIEW

**Comment by chillfig** [comment]
Hi @irowebbn , would you please add comments to this pull request? (example: https://github.com/nasa/CS/pull/43)

**Review by chillfig — APPROVED** [review]
The assert errors produced from 'CS_RecomputeAppChildTask_Test_DefEntryId()` shown in https://github.com/nasa/CS/issues/44 do not align with the unit test coverage results ran on main branch of nasa/cs. However, the change suggested is appropriate and maintains 100% unit coverage in nasa/cs. This pull requests requires pull request description and a contributor license agreement from the contributor before merging.

**Comment by irowebbn** [comment]
@chillfig Thanks for the help. I am waiting to hear back from my employer about permission for the CLA since this was discovered as part of my official duties.

**Comment by dzbaker** [comment]
@irowebbn CCB 13 October 2022: Pending CLA and PR description/linked issue.

**Comment by dzbaker** [comment]
26 January 2023: Ignoring while waiting on CLA.

**Comment by thnkslprpt** [comment]
> The assert errors produced from 'CS_RecomputeAppChildTask_Test_DefEntryId()` shown in #44 do not align with the unit test coverage results ran on main branch of nasa/cs...

Tests failing on nasa/CS main branch as well now (see https://github.com/thnkslprpt/CS/actions/runs/4333025360/jobs/7565890664#step:11:3742).

I will submit a PR with this change fixing the tests so that it doesn't start holding up other PRs.

**Pull request closed without merging**
